### ISSUE TITLE
App doesn't build/compile after `bundle exec pod install`

### ISSUE THREAD

**Issue by SrikanthKabadi** [grab/cocoapods-binary-cache#21] opened 2020-09-04 18:02 UTC
Hi,

I have a dependency on React Native in my project. Here is my snipped of pods in my Podfile.

  ```
plugin 'cocoapods-binary-cache'
platform :ios, '10.0'
install! 'cocoapods'

use_frameworks!

source 'https://cdn.cocoapods.org/'
source 'https://github.com/PhonePe/CustomPods.git'

config_cocoapods_binary_cache(
    prebuild_config: "Debug"
)

target 'PhonePe' do
pod 'React', '0.59.9.PhonePe', :subspecs => [
  'Core',
  'CxxBridge',
  'DevSupport',
  'RCTText',
  'RCTImage',
  'RCTNetwork',
  'RCTWebSocket',
  'RCTLinkingIOS',
  'RCTAnimation',
  'RCTGeolocation',
  'RCTActionSheet'
  ], :inhibit_warnings => true, :binary => true
  
  pod 'RNSVG', '9.5.1', :inhibit_warnings => true, :binary => true
  pod 'react-native-maps', '0.20.0', :inhibit_warnings => true, :binary => true
  pod 'SentryReactNative', '0.39.0', :inhibit_warnings => true, :binary => true
  pod 'GoogleMaps', :inhibit_warnings => true, :binary => true

end
```

With this Podfile,  If I run `bundle exec pod binary prebuild --push`, it prebuilds all these frameworks and pushes it to my remote repository as well. But when I try to build the app, compilation fails saying `"doubleconversion/doubleconversion.h"` file not found. Thing is, React uses `folly` and `DoubleConversion` frameworks as a dependency. This error triggers especially from `folly`. I even see `folly.framework` getting created once the prebuild command succeeds. 

But If I run the same prebuild command with extra addition in the configuration `prebuild_all_pods: "true"`, it prebuilds successfully + uploads it to the remote repository as well. Even when I compile the code, it builds successfully and I am able to run the app successfully.
```
config_cocoapods_binary_cache(
    prebuild_config: "Debug",
    prebuild_all_pods: "true"
)
```

But the same problem arises If I run `bundle exec pod install` right after prebuild command. It ends up showing the same build error as state above. 

This is what I have in my gem file as of (4th Sept 2020, 11:30pm IST)
```
source "https://rubygems.org"

gem "fastlane"
gem 'cocoapods', "= 1.9.3"
gem "cocoapods-binary-cache", :git => "https://github.com/grab/cocoapods-binary-cache.git", :branch => "master"
```

**Comment by trinhngocthuyen** [comment] 2020-09-07 13:14
Thanks for reaching out with details about the issue.
I managed to reproduce the issue on my side. 

As follows is the summary of the issue (as per scenarios I've tried out):

#### Scenario 1
Run the `prebuild` command. Then build the project --> **FAIL** ❌ .
Noticeably, the diagnosis when running the `prebuild` command spotted the errors:
```
Diagnosing cocoapods-binary-cache
🚩 Unintegrated frameworks: ["react-native-maps", "React", "RNSVG", "SentryReactNative", "Sentry", "DoubleConversion", "Folly", "glog", "yoga"]
```

#### Scenario 1
Given that those frameworks are available in the cache (by running a `prebuild` command beforehand).
Run pod installation. Then build the project --> **SUCCESSFUL** ✅ .

We'll look into the issue and keep you posted.
Thanks

**Comment by SrikanthKabadi** [comment] 2020-09-21 05:56
Hi @trinhngocthuyen ,

Thank you for validating the reported issue. 

If this issue is fixed, I was thinking to integrate this awesomely brilliant time-saving plugin in my project.

**Comment by trinhngocthuyen** [comment] 2020-09-21 10:58
We have found the root cause. It's due to some weirdly wrong sandbox state in the integration step.
We're working on a fix.

**Comment by trinhngocthuyen** [comment] 2020-09-23 04:06
Hi @SrikanthKabadi, the issue has been resolved in https://github.com/grab/cocoapods-binary-cache/commit/f4ee9226b31a6ce60b49152f620b5b8991b243fa.
Kindly check again if the fix is okay on your side.
Thanks for reporting the issue.

**Comment by SrikanthKabadi** [comment] 2020-09-23 20:18
Hi @trinhngocthuyen,

The fix is working beautifully. I am super happy and very excited to make use of this beautiful plugin :) Thank you so much again.

**Closed** 2020-09-24 01:09 UTC

**Comment by SrikanthKabadi** [comment] 2020-09-29 12:03
Hi @trinhngocthuyen,

This plugin worked for many of my internal frameworks. But unfortunately, it is failing to work for one of my framework called 'PerformanceX` with same error like above saying 

```
Diagnosing cocoapods-binary-cache
🚩 Unintegrated frameworks: ["PerformanceX"]
```

When I run `bundle exec pod binary prebuild --push`, this is what I see.
```
Start prebuild_frameworks
Prebuild frameworks (total 1): ["PerformanceX"]
xcodebuild command: xcodebuild -project <mypath>/_Prebuild/Pods.xcodeproj -scheme PerformanceX -configuration Debug -sdk iphonesimulator -destination id=8367C7D6-4BB8-46C7-94BD-71C128467C83 ARCHS=x86_64 ONLY_ACTIVE_ARCH=NO 2>&1
Targets to prebuild: ["PerformanceX"]
Targets to cleanup: []
Write prebuild changes to: _Prebuild_delta/changes.json


🚩 Unintegrated frameworks: ["PerformanceX"]
Pod installation complete! There are x dependencies from the Podfile and y total pods installed.
❯❯❯ Step: Syncing cache
- Update cache: PerformanceX
❯❯❯ Step: Pushing cache
Enumerating objects: 9, done.
Counting objects: 100% (9/9), done.
Delta compression using up to 12 threads
Compressing objects: 100% (5/5), done.
Writing objects: 100% (5/5), 1.27 KiB | 1.27 MiB/s, done.
Total 5 (delta 3), reused 0 (delta 0)
```
Could you please help me to understand what might be causing this issue? Or any potential fix?

**Comment by trinhngocthuyen** [comment] 2020-09-29 12:28
1/ First, I'd like to know about the degree of the issue.
Does it cause any build errors after running the above command? If it does, I'd suggest excluding this framework for temporary while investigating the issue.

2/ Some info needed for the investigation
- Is `PerformanceX` a development pod or an external-sources hosted pod?
- Does `PerformanceX` have subspecs (ex. `PerformanceX/<ASubspec>`)?

There might be something wrong with the podspec injection (needed for the integration). It would be better if you could share the structure of this podspec. Also, it would be easier to troubleshoot if we can have a demo project.

**Comment by SrikanthKabadi** [comment] 2020-09-30 14:03
Hi @trinhngocthuyen ,

`PerformanceX` earlier was a dev pod but I moved it to external-sources hosted pod. 

I understood the actual issue. It was related to `s.source_files` path. 

Earlier the path was like this. `s.source_files  = "PerformanceX/Sources/**/*.{swift,h,m}"`
Changing it to `s.source_files  = "**/PerformanceX/**/Sources/**/*.{swift,h,m}"` worked. 

Here is the Podspec guidelines
```
**File patterns**
Podspecs should be located at the root of the repository, and paths to files should be specified 
relative to the root of the repository as well. 
File patterns do not support traversing the parent directory ( .. ). 
```

The root of the repository did not have `PerformanceX` folder. But it used to work fine with local path(dev pod) `:path => "path_to_PerformanceX".

**Comment by trinhngocthuyen** [comment] 2020-10-01 02:52
Is the pod folder structure of `PerformanceX` like this?
```
root / --- PerformanceX.podspec
     | --- PerformanceX / --- Sources / --- 
```
if yes, then it should work correctly.

In this case, if the `source_files` caused the problem, then the issue should persist without this plugin as well.

Because of the invalid `source_files`, there are no source files of the framework integrated into the project when building it. Therefore, no products were produced. You can check it in the prebuild sandbox if `_Prebuild/GeneratedFrameworks/PerformanceX.zip` exists.

I suggest trying out the following options to understand more about the issue:
- Try disabling this plugin, run pod install and check the integration in the project (if the source files of this target are integrated or not)
- Try with different patterns in the podspecs:
   - `s.source_files = "**/PerformanceX/**/Sources/**/*.{swift,h,m}"`
   - `s.source_files = "**/PerformanceX/Sources/**/*.{swift,h,m}"`
   - `s.source_files = "PerformanceX/**/Sources/**/*.{swift,h,m}"`
   - `s.source_files = "PerformanceX/Sources/**/*.{swift,h,m}"`

Let us know if you find out anything interesting about it.

**Comment by SrikanthKabadi** [comment] 2020-10-05 11:49
Hi @trinhngocthuyen,

Pod folder structure is something like this:

```
root
--App/Podfile
--SharedPods/PerformanceX/PerformanceX.podspec
--SharedPods/PerformanceX/PerformanceX/Sources/
```

Earlier PerformanceX was a Dev pod. So I had it something like this in the `PerformanceX.podspec`
`s.source_files = "PerformanceX/Sources/**/*.{swift,h,m}"`

and in `Podfile`, it was like this.
`pod 'PerformanceX', :path => '../SharedPods/PerformanceX/PerformanceX.podspec'`

Later, I made it as an external source pod and made `Podfile` changes like this and it started to break. 
`pod 'PerformanceX', '1.0.0'`

As a matter of fact, it even Generated `_Prebuild/GeneratedFrameworks/PerformanceX/PerformanceX.framework` this. 

It even pushed the generated framework to my cache_repo but it was always showing the Diagnostic report saying `🚩 Unintegrated frameworks: ["PerformanceX"]` upon `binary exec pod binary prebuild --push` or `binary exec pod install`

This is the screenshot of generated and pushed `PerformanceX.framework` in my cache_repo.

<img width="962" alt="Screenshot 2020-10-05 at 5 14 29 PM" src="https://user-images.githubusercontent.com/2088715/95075742-57ed6d80-072e-11eb-8ddb-2afc9838e00e.png">
